<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
<title></title>
</head>

<body>
<h1>KmartApps</h1>
<ul>
  <li><a href="search_form.phtml">KSN Search</a></li>
  <li><a href="ksn_source.txt">Function to convert partial KSN to full in PHP</a></li>
</ul>


<hr>
<address></address>
<!-- hhmts start -->Last modified: Fri Jan 10 14:47:29 EST 2014 <!-- hhmts end -->
</body> </html>
