<html>
  <head>
    <style type="text/css">
      body {
      text-align:center;
      font-size: 36pt;


      }
      

      input[type=text] {
      border: 3px solid black;
      padding: 20px;

      }

      input[type=submit] {
      height:150px;
      }

      input[type=reset] {
      height: 150px;
      }

    </style>


  </head>
  <body>

      <h2>KSN Search Form</h2>

    <form action="search_results.phtml">

      <label>Keywords</label><br>
      <input style="width:100%" type="text" name="keyword" id="keyword" /><br><br>
      <input type="submit" name="submit" value="Search" />
      <input type="reset" name="clear" value="Clear" />


    </form>
  </body>
</html>
